FA.JustBlog.UI/Areas/Admin/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Repository.UnitOfWork;
using FA.JustBlog.UI.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Xml.Linq;

namespace FA.JustBlog.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = ("Blog Owner, Contributor"))]
    public class PostController : Controller
    {
        private IUnitOfWork uow;
        const int ITEMS_PER_PAGE = 3;
        public PostController(IUnitOfWork uow)
        {
            this.uow = uow;
        }
        public IActionResult Index([Bind(Prefix = "page")] int pageNumber)
        {
            if (pageNumber == 0)
                pageNumber = 1;
            var post = uow._post.GetAll();
            var totalItems = post.Count();
            int totalPages = (int)Math.Ceiling((double)totalItems / ITEMS_PER_PAGE);
            if (pageNumber > totalPages)
                return RedirectToAction(nameof(CommentController.Index), new { page = totalPages });
            var categorys = post
            .Skip(ITEMS_PER_PAGE * (pageNumber - 1))
            .Take(ITEMS_PER_PAGE)
            .ToList();
            ViewData["pageNumber"] = pageNumber;
            ViewData["totalPages"] = totalPages;
            return View(categorys.AsEnumerable());
        }
        public IActionResult GetlatesdPost()
        {
            var getlatedpost = uow._post.GetLatestPost(5);
            return View(getlatedpost.ToList());
        }
        public IActionResult GetMostPost()
        {
            var getmostpost = uow._post.GetMostViewedPost(5);
            return View(getmostpost.ToList());
        }
        [Authorize(Roles = ("Blog Owner"))]
        public IActionResult PublishedPosts()
        {
            var publishedpost = uow._post.GetPublisedPosts();
            return View(publishedpost.ToList());
        }
        [Authorize(Roles = ("Blog Owner"))]
        public IActionResult UnPublisherPost()
        {
            var unpublisherpost = uow._post.GetUnpublisedPosts();
            return View(unpublisherpost.ToList());
        }
        // GET: Test/Details/5
        public ActionResult PostDetails(int? id)
        {
            if (id.HasValue)
            {
                var postDetails = uow._post.Find(id.Value);
                if (postDetails != null)
                {
                    return View(postDetails);
                }
            }
           
            return RedirectToAction(nameof(Index));
        }

        // GET: Test/Create
        [Authorize(Roles = ("Blog Owner, Contributor"))]
        public ActionResult Create()
        {
            var category = uow._category.GetAll();
            ViewData["categories"] = new MultiSelectList(category, "Id", "Name");
            return View();
        }

        // POST: Test/Create
        [Authorize(Roles = ("Blog Owner, Contributor"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PostModels post)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    uow._post.Add(new Post() {Title = post.Title, ShortDescription = post.ShortDescription, PostContent = post.PostContent, UrlSlug = post.UrlSlug, Published = post.Published, PostedOn = post.PostedOn, Modified = post.Modified,ViewCount = post.ViewCount,RateCount = post.RateCount,TotalRate = post.TotalRate, CategoryId =  post.CategoryId});
                    uow.SaveChange();
                    return Redirect("/Admin/Post/Index");
                }
            }
            catch
            {
                return View();
            }
            return View(post);
        }

        // GET: Test/Edit/5
        //[Authorize(Roles = ("Blog Owner, Contributor"))]
        public ActionResult Edit(int? id)
        {
            var category = uow._category.GetAll();
            ViewData["categories"] = new MultiSelectList(category, "Id", "Name");
            if (id.HasValue)
            {
                var postEdit = uow._post.Find(id.Value);
                if (postEdit != null)
                {
                    return View(postEdit);
                }
            }
            return Redirect("/Admin/Post/Index");
        }

        // POST: Test/Edit/5
        //[Authorize(Roles = ("Blog Owner, Contributor"))]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, PostModels post)
        {

            if (id != post.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    if (id.HasValue)
                    {
                        uow._post.Update(new Post() {Id = post.Id, Title = post.Title, ShortDescription = post.ShortDescription, PostContent = post.PostContent, UrlSlug = post.UrlSlug, Published = post.Published, PostedOn = post.PostedOn, Modified = post.Modified, ViewCount = post.ViewCount, RateCount = post.RateCount, TotalRate = post.TotalRate, CategoryId = post.CategoryId });
                        uow.SaveChange();
                    }
                }
                catch (InvalidOperationException ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
                return Redirect("/Admin/Post/Index");
            }
            return View(post);
        }
        // POST: Test/Delete/5
        [Authorize(Roles = ("Blog Owner"))]
        public ActionResult Delete(int? id)
        {
            if (id.HasValue)
            {
                uow._post.Delete(id.Value);
                uow.SaveChange();
            }
            return Redirect("/Admin/Post/Index");
        }
    }
}

FA.JustBlog.UI/Views/Shared/_Layout.cshtml
@using FA.JustBlog.Core.Models;
@using FA.JustBlog.Core.Repository.UnitOfWork;

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Just Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico"/>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
       <link href="~/css/site.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">JustBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="@Url.Action("Index", "Home")">Home</a></li>
                        @if(User.Identity?.IsAuthenticated ?? false)
                    {
                        if(User.IsInRole("Blog Owner") || User.IsInRole("Contributor"))
                        {
                             <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="@Url.Action("Index","Home",new{area = "Admin"})">Admin</a></li>
                        }
                    }
                   
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" asp-action="Index" asp-controller="Post">Post</a></li>
                        <li class="dropdown nav-item"><a class="nav-link px-lg-3 py-lg-4 dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Category</a>
                        @{
                            IUnitOfWork unitOfWork = new UnitOfWork();
                            var ListCategoryName = unitOfWork._category.GetAll();
                        }
                        <ul class="dropdown-menu">
                            @foreach(Category item in ListCategoryName)
                            {
                                <li>
                                    <a class="dropdown-item" href="@Url.Action("GetPostByCategory", "Post",new{category = item.Name})">@item.Name</a>
                                </li>
                            }
                        </ul>
                        </li>
                       @if (User.Identity?.IsAuthenticated ?? false)
                       {
                             <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4">Hello @User.Identity.Name </a></li>
                             <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/Identity/Account/Logout">Log Out</a></li>
                       }
                       else
                       {
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/Identity/Account/Login">Login</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/Identity/Account/Register">Sign Up</a></li>
                       }
                    </ul>
                </div>
            </div>
        </nav>       
       @RenderBody()
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; DatHV5</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
       <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
    @RenderSection("scripts",required:false)
    </body>
</html>